print("src/apps/SConscript...")

Import('env')

#libraries = [
#    'aux',  'gst',  'gmp',  'ffi',  'ltdl', 'snprintfv',
#    'sigsegv', 'poll'
#]
env.Program('gst', ['main.c', '#lib/logc/log.c'])
env.Program('gst-tool', 'gst-tool.c')
